### ISSUE TITLE
Get Zharta listed on DefiLlama for 0.25ETH

### ISSUE THREAD

**Issue by marcodinissantos** [Zharta/bounties#2]
### 📃 GOAL
The goal of this bounty is to get [Zharta's platform](https://app.zharta.io) listed on [https://defillama.com/protocols/NFT%20Lending](https://defillama.com/protocols/NFT%20Lending)
The prize will be 0.25ETH paid in case of success, after the bounty is fulfilled, to a wallet to be designated by the winner of the bounty.

### 🛠️HOW
In order to get Zharta listed there, you must follow the instructions set here: [https://docs.llama.fi/list-your-project/submit-a-project](https://docs.llama.fi/list-your-project/submit-a-project)
You may also need to consult Zharta's documentation, present at: [https://zharta.gitbook.io/zharta-welcome-kit/overview/introducing-zharta](https://zharta.gitbook.io/zharta-welcome-kit/overview/introducing-zharta)

**Comment by developerfred** [comment]
@marcodinissantos  
done here: https://github.com/DefiLlama/DefiLlama-Adapters/pull/5428

**Comment by ginanisque** [comment]
Hi! I have applied to work on this bounty. I can get it listed. I will be will to work on this. Thanks.
